/* SAMPLE COLLECTORS */
export const GET_LABS_TESTING = "GET_LABS_TESTING";
export const GET_LABS_TESTING_SUCCESS =
  "GET_LABS_TESTING_SUCCESS";
export const GET_LABS_TESTING_FAIL = "GET_LABS_TESTING_FAIL";
