/* LAB PROFILE */
export const GET_DOCTOR_PROFILE = "GET_DOCTOR_PROFILE";
export const GET_DOCTOR_PROFILE_SUCCESS = "GET_DOCTOR_PROFILE_SUCCESS";
export const GET_DOCTOR_PROFILE_FAIL = "GET_DOCTOR_PROFILE_FAIL";


export const UPDATE_DOCTOR_PROFILE = "UPDATE_DOCTOR_PROFILE";
export const UPDATE_DOCTOR_PROFILE_SUCCESS =
  "UPDATE_DOCTOR_PROFILE_SUCCESS";
export const UPDATE_DOCTOR_PROFILE_FAIL = "UPDATE_DOCTOR_PROFILE_FAIL";

