/* DONOR_ACCOUNT_STATEMENTS */
export const GET_DONORS_ACCOUNT_STATEMENTS = "GET_DONORS_ACCOUNT_STATEMENTS";
export const GET_DONORS_ACCOUNT_STATEMENTS_SUCCESS = "GET_DONORS_ACCOUNT_STATEMENTS_SUCCESS";
export const GET_DONORS_ACCOUNT_STATEMENTS_FAIL = "GET_DONORS_ACCOUNT_STATEMENTS_FAIL";
